steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-f', 'Dockerfile',
            '-t','gcr.io/$PROJECT_ID/message-store',
            '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/message-store'