version: '3'
services:
  app:
    container_name: "message-store"
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true